FROM golang:1.19.4-alpine3.17 AS builder

RUN mkdir /build
WORKDIR /build
COPY go.* .
RUN go mod download
COPY . .

RUN go build -o pismo

FROM alpine:3.17
COPY --from=builder /build/pismo /app/

WORKDIR /app
CMD ["./pismo"]
