version: '3' 

services:
  pismo-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: pismo
    restart: always
    ports:
      - 8080:8080
    environment:
      REST_PORT: 8080
      # TODO: don't hardcode credentials
      DB_HOST: pismo-db
      DB_PORT: 5432
      DB_USER: pismo
      DB_PASSWORD: pismo
      DB_DBNAME: pismo

  pismo-db:
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432
    environment:
      # TODO: don't hardcode credentials
      POSTGRES_USER: pismo
      POSTGRES_PASSWORD: pismo
      POSTGRES_DB: pismo
    volumes:
      - pismo-data:/var/lib/postgresql/data

  pismo-dbinit:
    build:
      context: .
      dockerfile: Dockerfile.dbinit
    image: pismo-dbinit
    restart: 'on-failure:2'
    environment:
      # TODO: don't hardcode credentials
      DB_HOST: pismo-db
      DB_PORT: 5432
      DB_USER: pismo
      DB_PASSWORD: pismo
      DB_DBNAME: pismo

volumes:
  pismo-data:
