version: '3' 

services:
  pismo-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: ${API_SERVER_IMAGE}
    restart: always
    ports:
      - ${REST_PORT}:${REST_PORT}
    environment:
      REST_PORT: ${REST_PORT}
      DB_HOST: pismo-db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DBNAME: pismo
    depends_on:
      - pismo-db
      - pismo-dbinit

  pismo-dbinit:
    build:
      context: .
      dockerfile: Dockerfile.dbinit
    image: ${DB_INIT_IMAGE}
    restart: 'on-failure:2'
    environment:
      DB_HOST: pismo-db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DBNAME: pismo
    depends_on:
      - pismo-db

  pismo-db:
    image: ${POSTGRES_IMAGE}
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: pismo
    volumes:
      - pismo-data:/var/lib/postgresql/data

volumes:
  pismo-data:
