// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"time"
)

type Account struct {
	ID             int32
	DocumentNumber string
	Balance        int64
}

type OperationType struct {
	ID          int32
	Description string
}

type Transaction struct {
	ID              int32
	AccountID       int32
	OperationTypeID int32
	Amount          int64
	CreatedAt       time.Time
}
